// @ts-nocheck
// GENERATED by scripts/build-edge.mjs from server/core.js, server/pg.js and server/http.js. Do not edit by hand.
//
// Lightech Mentoring App API — Supabase Edge Function "api".
// Env (set automatically by Supabase): SUPABASE_DB_URL.  Optional: ALLOWED_ORIGINS="https://crm.example.com".
// "Verify JWT" must be OFF for this function: the app signs people in itself (supabase/config.toml does this).
import postgres from 'npm:postgres@3.4.4';

/**
 * Lightech Mentoring App — server core (storage-agnostic)
 * -------------------------------------------------------------------------
 * Sign-in, per-company (tenant) isolation, least-privilege visibility, the public lead form and the audit trail.
 * The same code runs in the Supabase Edge Function (supabase/functions/api) and in the Node test harness.
 *
 * A host (server/pg.js) preloads the records a request can touch into an in-memory store, runs handle_()
 * synchronously, then persists the pending writes in the same database transaction.
 *
 * Request  : POST text/plain JSON { action, token?, ... }
 * Response : JSON { ok: true, ... } | { ok: false, error: 'auth' | 'forbidden' | 'locked' | 'suspended' | 'invalid' | 'not_found' | 'setup_required', message }
 */
import { createHash, pbkdf2Sync, randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';
import { Buffer } from 'node:buffer';

const VERSION = '2.0.0';

// host: { store, cache, audit(row), auditRows(wsId|null, limit) → rows, setupCode() → string|'', consumeSetup(), log(msg) }
function createCore(host) {
const load_ = function () { return host.store; };
const cache_ = function () { return host.cache; };
const audit_ = function (actor, company, action, path, detail) { host.audit([new Date(), actor, company, action, path, detail || '']); };
const auditMany_ = function (rows) { rows.forEach(function (r) { host.audit(r); }); };
const auditRows_ = function (wsId, limit) { return host.auditRows(wsId, limit); };
const uuid_ = function () { return randomUUID(); };
const jakartaDate_ = function (d) { return new Date(d.getTime() + 7 * 3600 * 1000).toISOString().slice(0, 10); };
const LockService = { getScriptLock: function () { return { waitLock: function () {}, releaseLock: function () {} }; } }; // the host serializes writers

const SESSION_HOURS = 8;              // token lifetime
const MAX_FAILED_LOGINS = 5;          // per email, then locked for LOCK_MINUTES
const LOCK_MINUTES = 15;

function handle_(req) {
  const a = String(req.action || '');
  const t0 = Date.now() - 5000; // overlap window: rows written while we read are re-sent next poll (clients de-duplicate)
  if (a === 'ping') return { ok: true, version: VERSION, setup: !hasPlatform_() };
  if (a === 'setup') return setup_(req);
  if (a === 'brand' || a === 'login') { if (!hasPlatform_()) return { ok: false, error: 'setup_required', message: 'This server has not been set up yet.' }; }
  if (a === 'brand') return brand_(req);
  if (a === 'login') return login_(req);
  if (a === 'capture') return capture_(req);
  const sess = session_(req.token);
  if (!sess) return { ok: false, error: 'auth', message: 'Session expired. Please sign in again.' };
  switch (a) {
    case 'whoami': return { ok: true, session: publicSession_(sess) };
    case 'password': return changePassword_(sess, req);
    case 'logout': cache_().remove('tok:' + req.token); return { ok: true };
    case 'list': return list_(sess, req.collection, t0);
    case 'get': return get_(sess, req.path);
    case 'batch': return batch_(sess, req.ops || []);
    case 'changes': return changes_(sess, Number(req.since) || 0, t0);
    case 'audit': return auditList_(sess, Number(req.limit) || 200);
  }
  return { ok: false, error: 'invalid', message: 'Unknown action' };
}

// ───────────────────────────────────────────────────────── one-time setup
// The database migration stores a random setup code (shown once in the SQL editor). Whoever holds it creates the
// Lightech Super Admin with their own password and, optionally, the AlphaLeaders workspace with the whole team.
// The code is consumed on success, so setup can never run twice.
function hasPlatform_() { return !!data_(load_(), 'platform/main'); }
function setup_(req) {
  if (hasPlatform_()) return { ok: false, error: 'forbidden', message: 'Already set up.' };
  const c = cache_();
  const fails = Number(c.get('fail:setup') || 0);
  if (fails >= MAX_FAILED_LOGINS) return { ok: false, error: 'locked', message: 'Too many failed attempts. Try again in ' + LOCK_MINUTES + ' minutes.' };
  const code = String(host.setupCode() || '');
  const given = String(req.code || '').trim();
  if (!code || !sameHex_(given, code)) {
    c.put('fail:setup', String(fails + 1), LOCK_MINUTES * 60);
    audit_('setup', 'lightech', 'setup_failed', '', 'wrong setup code');
    return { ok: false, error: 'invalid', message: 'Wrong setup code.' };
  }
  const email = String(req.email || '').trim().toLowerCase();
  const name = String(req.name || '').trim().slice(0, 80) || 'Lightech Super Admin';
  const pw = String(req.password || '');
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return { ok: false, error: 'invalid', message: 'Enter a valid email.' };
  if (pw.length < 10) return { ok: false, error: 'invalid', message: 'Use at least 10 characters for the Super Admin password.' };
  const store = load_();
  const admin = { id: 'lt-owner', name: name, email: email, role: 'owner', active: true };
  setPassword_(admin, pw);
  writeDocs_(store, [{ op: 'set', path: 'platform/main', data: { name: 'Lightech', admins: [admin] } }], 'setup');
  audit_(email, 'lightech', 'setup', 'platform/main', 'Created Lightech Super Admin ' + email);
  host.consumeSetup();
  const out = { ok: true, admin: { name: name, email: email }, team: [] };
  if (req.alphaleaders) out.team = createAlphaLeaders_(store);
  return out;
}
// The whole AlphaLeaders team; each gets a one-time password and must choose their own at first sign-in.
// Emails can be changed by the Owner in Team & Access.
const FIRST_COMPANY = {
  slug: 'alphaleaders',
  team: [
    { id: 'u-owner', name: 'Coach Ferly F Raya', email: 'ferly@alphaleaders.id', role: 'superadmin', coach: true },
    { id: 'u-ferry', name: 'Ferry Davira', email: 'ferry@alphaleaders.id', role: 'superadmin', coach: true },
    { id: 'u-lisa', name: 'Tami', email: 'tami@alphaleaders.id', role: 'admin' },
    { id: 'u-anita', name: 'Anita', email: 'anita@alphaleaders.id', role: 'admin' },
    { id: 'm-hendra', name: 'Josshhua Abraham', email: 'josshhua@alphaleaders.id', role: 'mentor' },
    { id: 'm-sylvia', name: 'Anthony Sihombing', email: 'anthony@alphaleaders.id', role: 'mentor' },
    { id: 'm-alvin', name: 'Wulansari Suharto', email: 'wulansari@alphaleaders.id', role: 'mentor' },
    { id: 'm-charles', name: 'Charles Suryana', email: 'charles@alphaleaders.id', role: 'mentor' },
    { id: 'm-malvin', name: 'Malvin Haryanto', email: 'malvin@alphaleaders.id', role: 'mentor' },
    { id: 'm-rizki', name: 'Rizki Esa', email: 'rizki@alphaleaders.id', role: 'mentor' },
    { id: 'b-rina', name: 'Julia', email: 'julia@alphaleaders.id', role: 'bd' },
    { id: 'b-fajar', name: 'Paul', email: 'paul@alphaleaders.id', role: 'bd' }
  ]
};
// Creates the AlphaLeaders company (brand, funnel, programs, whole team) and returns each person's one-time password.
function createAlphaLeaders_(store) {
  if (metas_(store).some(function (m) { return slugOf_(m) === FIRST_COMPANY.slug; })) return [];
  const team = [];
  const owners = FIRST_COMPANY.team.map(function (o) {
    const a = { id: o.id, name: o.name, email: o.email, role: o.role, active: true, mustChange: true };
    if (o.coach) a.coach = true;
    const pw = randomPassword_(); setPassword_(a, pw);
    team.push({ name: a.name, email: a.email, role: a.role, password: pw });
    return a;
  });
  const id = 'ws-' + uuid_().replace(/-/g, '').slice(0, 12);
  const meta = {
    name: 'AlphaLeaders', slug: FIRST_COMPANY.slug, status: 'active', preset: 'alphaleaders', createdAt: new Date().toISOString(), v: 3,
    config: {
      brandName: 'AlphaLeaders', tagline: 'Coaching CRM · Lead to Deal', accent: '#1c1c1c', currency: 'IDR', demoLogin: false, publicForm: false,
      logo: 'assets/brands/alphaleaders-logo.png', mark: 'assets/brands/alphaleaders-mark.png', bar: '#0a0a0a', bar2: '#1d1d1d', gold: '#d4a537',
      labels: { lead: 'Lead', leads: 'Leads', client: 'Client', clients: 'Clients', mentor: 'Coach', mentors: 'Coaches', session: 'Session', sessions: 'Sessions', program: 'Program', programs: 'Programs', owner: 'BD / Sales' },
      stages: [
        { id: 'new', name: 'New Lead', color: '#64748b', prob: 5, sla: 2, type: 'open' },
        { id: 'cov', name: 'COV Call (15m)', color: '#0284c7', prob: 15, sla: 3, type: 'open' },
        { id: 'abm', name: 'ABM Mapping (2–3h)', color: '#d97706', prob: 40, sla: 7, type: 'open' },
        { id: 'abe', name: 'ABE Closing (2h)', color: '#7c3aed', prob: 70, sla: 7, type: 'open' },
        { id: 'won', name: 'Deal Won', color: '#16a34a', prob: 100, sla: 0, type: 'won' },
        { id: 'lost', name: 'Lost', color: '#dc2626', prob: 0, sla: 0, type: 'lost' }
      ],
      sessionTypes: [
        { id: 'st-cov', name: 'COV Call', duration: 15, color: '#0284c7', stageId: 'cov' },
        { id: 'st-abm', name: 'ABM Assessment & Mapping', duration: 150, color: '#d97706', stageId: 'abm' },
        { id: 'st-abe', name: 'ABE Proposal & Closing', duration: 120, color: '#7c3aed', stageId: 'abe' },
        { id: 'st-coach', name: 'Coaching Session', duration: 120, color: '#16a34a', stageId: '' },
        { id: 'st-review', name: 'Review / Induction', duration: 60, color: '#0f766e', stageId: '' }
      ],
      sources: ['Meta Ads', 'Google Ads', 'Referral', 'Organic / Social', 'Event / Seminar', 'BD Relation', 'Walk-in', 'Website form'],
      lostReasons: ['Budget not ready', 'Timing not right', 'Chose a competitor', 'Unresponsive', 'Not qualified'],
      waTemplate: 'Hi {name}, a quick reminder of your {type} with {mentor} on {date} at {time} WIB. See you there! — {brand}',
      commission: { rate: 10, target: 0, bonus: 0 }
    },
    accounts: owners,
    programs: [
      { id: 'p-private', name: '1-Year Private Coaching', format: 'Private', price: 120000000, sessions: 24, months: 12 },
      { id: 'p-group', name: '1-Year Group Mastermind', format: 'Group', price: 36000000, sessions: 24, months: 12 },
      { id: 'p-abm', name: 'Business Mapping (ABM only)', format: 'Private', price: 7500000, sessions: 1, months: 1 }
    ]
  };
  writeDocs_(store, [{ op: 'set', path: 'ws/' + id, data: meta }], 'setup');
  audit_('setup', id, 'save', 'ws/' + id, 'Created AlphaLeaders with ' + owners.length + ' accounts: ' + owners.map(function (a) { return a.email; }).join(', '));
  return team;
}

// ───────────────────────────────────────────────────────── auth
function login_(req) {
  const email = String(req.email || '').trim().toLowerCase();
  const pw = String(req.password || '');
  const slug = String(req.slug || '').trim().toLowerCase();
  if (!email || !pw) return { ok: false, error: 'invalid', message: 'Email and password are required.' };
  const c = cache_();
  const fails = Number(c.get('fail:' + email) || 0);
  if (fails >= MAX_FAILED_LOGINS) return { ok: false, error: 'locked', message: 'Too many failed attempts. Try again in ' + LOCK_MINUTES + ' minutes.' };
  const store = load_();
  let sess = null, suspended = false;
  if (!slug) {
    const plat = data_(store, 'platform/main') || { admins: [] };
    const adm = (plat.admins || []).filter(function (x) { return (x.email || '').toLowerCase() === email && x.active !== false; })[0];
    if (adm && checkPassword_(adm, pw)) sess = { kind: 'platform', adminId: adm.id, role: adm.role, name: adm.name, email: adm.email };
  }
  if (!sess) {
    const metas = metas_(store);
    for (let i = 0; i < metas.length && !sess; i++) {
      const w = metas[i];
      if (slug && slugOf_(w) !== slug) continue;
      const acc = (w.data.accounts || []).filter(function (x) { return (x.email || '').toLowerCase() === email && x.active !== false; })[0];
      if (acc && checkPassword_(acc, pw)) {
        if (w.data.status === 'suspended') { suspended = true; continue; }
        sess = { kind: 'tenant', wsId: w.id, accountId: acc.id, role: acc.role, name: acc.name, email: acc.email };
      }
    }
  }
  if (!sess) {
    if (suspended) return { ok: false, error: 'suspended', message: 'This workspace is inactive. Contact your administrator.' };
    c.put('fail:' + email, String(fails + 1), LOCK_MINUTES * 60);
    audit_(email, slug, 'login_failed', '', 'attempt ' + (fails + 1));
    return { ok: false, error: 'invalid', message: 'Wrong email or password.' };
  }
  c.remove('fail:' + email);
  const token = uuid_() + uuid_().replace(/-/g, '');
  sess.exp = Date.now() + SESSION_HOURS * 3600 * 1000;
  c.put('tok:' + token, JSON.stringify(sess), SESSION_HOURS * 3600);
  audit_(sess.email, sess.wsId || 'lightech', 'login', '', sess.kind + ' · ' + sess.role);
  return { ok: true, token: token, session: publicSession_(sess) };
}

function session_(token) {
  if (!token) return null;
  const raw = cache_().get('tok:' + token);
  if (!raw) return null;
  const s = JSON.parse(raw);
  if (s.exp && s.exp < Date.now()) return null;
  // Re-check that the account is still active and the company not suspended.
  const store = load_();
  if (s.kind === 'platform') {
    const plat = data_(store, 'platform/main') || { admins: [] };
    const adm = (plat.admins || []).filter(function (x) { return x.id === s.adminId && x.active !== false; })[0];
    if (!adm) return null;
    s.role = adm.role;
  } else {
    const meta = data_(store, 'ws/' + s.wsId);
    if (!meta || meta.status === 'suspended') return null;
    const acc = (meta.accounts || []).filter(function (x) { return x.id === s.accountId && x.active !== false; })[0];
    if (!acc) return null;
    s.role = acc.role;
  }
  s.store = store;
  return s;
}
const publicSession_ = function (s) { return { kind: s.kind, wsId: s.wsId || '', accountId: s.accountId || '', adminId: s.adminId || '', role: s.role, name: s.name, email: s.email }; };

// Public branding for a company's own sign-in page (no other company, no password hashes).
function brand_(req) {
  const slug = String(req.slug || '').trim().toLowerCase();
  const w = metas_(load_()).filter(function (m) { return slugOf_(m) === slug; })[0];
  if (!w) return { ok: false, error: 'not_found', message: 'Unknown company code.' };
  const c = w.data.config || {};
  const byRole = {};
  if (c.demoLogin) (w.data.accounts || []).forEach(function (a) { if (a.active !== false && !byRole[a.role]) byRole[a.role] = { id: a.id, name: a.name, role: a.role, email: a.email }; });
  return {
    ok: true, id: w.id, slug: slugOf_(w), status: w.data.status || 'active', name: w.data.name,
    config: { brandName: c.brandName, tagline: c.tagline, accent: c.accent, logo: c.logo || '', mark: c.mark || '', bar: c.bar || '', bar2: c.bar2 || '', gold: c.gold || '', labels: c.labels, demoLogin: !!c.demoLogin, publicForm: !!c.publicForm, stages: [], sessionTypes: [], sources: [], lostReasons: [] },
    programs: c.publicForm ? (w.data.programs || []).map(function (p) { return { id: p.id, name: p.name }; }) : [],
    chips: Object.keys(byRole).map(function (k) { return byRole[k]; })
  };
}

// ───────────────────────────────────────────────────────── public lead form
// Anyone can submit; only to a company that switched its form on. Spam guards: honeypot field, per-company and
// per-phone rate limits, field length caps. New leads are assigned round-robin to the BD with the fewest open leads.
const CAPTURE_PER_10_MIN = 30;
function capture_(req) {
  if (req.website) return { ok: true }; // honeypot filled in: a bot. Pretend success, store nothing.
  const slug = String(req.slug || '').trim().toLowerCase();
  const clip = function (v, n) { return String(v == null ? '' : v).replace(/[\u0000-\u001f]/g, ' ').trim().slice(0, n); };
  const name = clip(req.name, 80), phone = clip(req.phone, 20).replace(/[^\d+]/g, '');
  if (!name || phone.replace(/\D/g, '').length < 8) return { ok: false, error: 'invalid', message: 'Name and a valid WhatsApp number are required.' };
  const c = cache_();
  const n = Number(c.get('cap:' + slug) || 0);
  if (n >= CAPTURE_PER_10_MIN) return { ok: false, error: 'busy', message: 'Too many submissions. Please try again later.' };
  c.put('cap:' + slug, String(n + 1), 600);
  const digits = phone.replace(/\D/g, '').replace(/^0/, '62');
  if (c.get('capp:' + slug + ':' + digits)) return { ok: true, duplicate: true }; // double-click / resubmit
  const lock = LockService.getScriptLock();
  lock.waitLock(20000);
  try {
    const store = load_();
    const w = metas_(store).filter(function (m) { return slugOf_(m) === slug; })[0];
    if (!w || w.data.status === 'suspended' || !(w.data.config || {}).publicForm) return { ok: false, error: 'closed', message: 'This form is not available.' };
    const cfg = w.data.config, base = 'ws/' + w.id;
    const leads = store.rows.filter(function (r) { return !r.deleted && r.parent === base + '/leads'; }).map(function (r) { return JSON.parse(r.json); });
    const norm = function (x) { return String(x || '').replace(/\D/g, '').replace(/^0/, '62'); };
    if (leads.some(function (l) { return norm(l.phone) === digits; })) { audit_('web form', w.id, 'capture_duplicate', '', name); return { ok: true, duplicate: true }; }
    const stages = cfg.stages || [];
    const first = stages.filter(function (x) { return x.type === 'open'; })[0] || stages[0] || { id: 'new' };
    const openIds = {}; stages.forEach(function (x) { if (x.type === 'open') openIds[x.id] = 1; });
    const owner = pickOwner_(w.data.accounts || [], leads, openIds);
    const prog = (w.data.programs || []).filter(function (p) { return p.id === req.programId; })[0];
    // Campaign source from the link (&src=): matched to a known source, else kept as typed (cleaned), else "Website form".
    const rawSrc = clip(req.source, 40).replace(/[^A-Za-z0-9 _.\-\/&]/g, '');
    const src = (cfg.sources || []).filter(function (x) { return x.toLowerCase() === rawSrc.toLowerCase(); })[0] || rawSrc || 'Website form';
    const now = new Date(), iso = now.toISOString();
    const lead = {
      id: 'L' + uuid_().replace(/-/g, '').slice(0, 12), name: name, phone: phone, email: clip(req.email, 120), company: clip(req.company, 120),
      source: src, ownerId: owner, programId: prog ? prog.id : '', value: prog ? Number(prog.price) || 0 : 0, stageId: first.id,
      nextAction: 'WhatsApp follow-up (web form)', nextActionDate: jakartaDate_(now),
      notes: clip(req.message, 1000), createdAt: iso, updatedAt: iso, createdBy: 'web-form',
      history: [{ at: iso, from: null, to: first.id, note: 'Web form', by: 'web-form' }]
    };
    if (cfg.testMode) lead.demo = true; // testing (UAT) period: removable with "Delete example & test data"
    writeDocs_(store, [{ op: 'set', path: base + '/leads/' + lead.id, data: lead }], 'web form');
    audit_('web form', w.id, 'capture', base + '/leads/' + lead.id, name + ' → ' + owner);
    c.put('capp:' + slug + ':' + digits, '1', 600);
    return { ok: true };
  } finally { lock.releaseLock(); }
}
// Round-robin by workload: the active BD with the fewest open leads; falls back to the Owner.
function pickOwner_(accounts, leads, openIds) {
  const bds = accounts.filter(function (a) { return a.role === 'bd' && a.active !== false; });
  const pool = bds.length ? bds : accounts.filter(function (a) { return a.role === 'superadmin' && a.active !== false; });
  if (!pool.length) return '';
  const load = {}; pool.forEach(function (a) { load[a.id] = 0; });
  leads.forEach(function (l) { if (openIds[l.stageId] && load[l.ownerId] != null) load[l.ownerId]++; });
  return pool.slice().sort(function (a, b) { return load[a.id] - load[b.id]; })[0].id;
}

// ───────────────────────────────────────────────────────── authorization
// Least privilege: every record is either fully visible, visible as numbers only (leaderboard / funnel), or hidden.
const FULL_ROLES_ = ['superadmin', 'admin', 'senior'];
function inCompany_(s, path) {
  if (s.kind === 'platform') return true;
  const base = 'ws/' + s.wsId;
  return path === base || path.indexOf(base + '/') === 0;
}
// Per-request visibility for limited roles (bd, mentor, assistant, client). null = sees everything in the company.
function scope_(s) {
  if (s.kind === 'platform' || FULL_ROLES_.indexOf(s.role) >= 0) return null;
  if (s._scope) return s._scope;
  const base = 'ws/' + s.wsId;
  const meta = data_(s.store, base) || {};
  const me = (meta.accounts || []).filter(function (a) { return a.id === s.accountId; })[0] || {};
  const leads = {}, sessions = {}, clients = {};
  s.store.rows.forEach(function (r) {
    if (r.deleted) return;
    if (r.parent === base + '/leads') leads[r.path] = JSON.parse(r.json);
    else if (r.parent === base + '/sessions') sessions[r.path] = JSON.parse(r.json);
    else if (r.parent === base + '/clients') clients[r.path] = JSON.parse(r.json);
  });
  const sc = { full: {}, numbers: {}, me: me };
  const leadFull = {};
  const each = function (o, fn) { Object.keys(o).forEach(function (k) { fn(k, o[k]); }); };
  if (s.role === 'client') {
    const c = clients[base + '/clients/' + me.clientId];
    if (c) { sc.full[base + '/clients/' + me.clientId] = 1; leadFull[c.leadId] = 1; }
    each(sessions, function (p, x) { if (leadFull[x.leadId]) sc.full[p] = 1; });
    each(leads, function (p, x) { if (leadFull[x.id]) sc.full[p] = 1; });
    return (s._scope = sc);
  }
  if (s.role === 'bd') {
    each(leads, function (p, x) { if (x.ownerId === s.accountId) leadFull[x.id] = 1; });
    each(sessions, function (p, x) { if (leadFull[x.leadId]) sc.full[p] = 1; });
    each(clients, function (p, x) { if (leadFull[x.leadId]) sc.full[p] = 1; });
  } else if (s.role === 'mentor' || s.role === 'assistant') {
    const coach = s.role === 'assistant' ? me.mentorId : s.accountId;
    if (s.role === 'assistant') each(leads, function (p, x) { leadFull[x.id] = 1; }); // assistants manage all leads
    each(sessions, function (p, x) { if (x.mentorId === coach || x.assistantId === s.accountId) { sc.full[p] = 1; leadFull[x.leadId] = 1; } });
    each(clients, function (p, x) { if (x.coachId === coach || x.assistantId === s.accountId) { sc.full[p] = 1; leadFull[x.leadId] = 1; } });
  }
  each(leads, function (p, x) { if (leadFull[x.id]) sc.full[p] = 1; else sc.numbers[p] = 1; });
  return (s._scope = sc);
}
function visibility_(s, path) {
  if (!inCompany_(s, path)) return 'none';
  if (path === 'platform/main') return s.kind === 'platform' ? 'full' : 'none';
  const sc = scope_(s);
  if (!sc || /^ws\/[^/]+$/.test(path)) return 'full';
  if (sc.full[path]) return 'full';
  if (sc.numbers[path]) return 'numbers';
  return 'none';
}
function canRead_(s, path) { return visibility_(s, path) !== 'none'; }
function canWrite_(s, op, path) {
  if (s.kind === 'platform') return op === 'set' || s.role === 'owner' || !/^ws\/[^/]+$/.test(path); // only the Super Admin deletes companies
  if (!inCompany_(s, path)) return false;
  const base = 'ws/' + s.wsId;
  const admin = s.role === 'superadmin' || s.role === 'admin';
  if (path === base) return admin && op === 'set';
  const exists = !!data_(s.store, path);
  if (exists && scope_(s) && visibility_(s, path) !== 'full') return false; // cannot change records you cannot fully see
  if (op === 'del') return admin || (path.indexOf(base + '/sessions/') === 0 && s.role !== 'client' && s.role !== 'bd');
  if (s.role === 'client') return exists && path.indexOf(base + '/sessions/') === 0; // clients only tick action items on their own sessions
  return true;
}

// ───────────────────────────────────────────────────────── data actions
function list_(s, collection, t0) {
  collection = String(collection || '');
  const rows = s.store.rows.filter(function (r) { return r.parent === collection && !r.deleted && canRead_(s, r.path); });
  return { ok: true, now: t0, docs: rows.map(function (r) { return { id: r.path.split('/').pop(), data: redact_(s, r.path, JSON.parse(r.json)) }; }) };
}
function get_(s, path) {
  path = String(path || '');
  if (!canRead_(s, path)) return { ok: false, error: 'forbidden', message: 'No access.' };
  const d = data_(s.store, path);
  return { ok: true, exists: !!d, data: d ? redact_(s, path, d) : null };
}
const RECORD_PATH_ = /^(platform\/main|ws\/[A-Za-z0-9_\-.~:@+]{1,80}(\/(leads|sessions|clients)\/[A-Za-z0-9_\-.~:@+]{1,80})?)$/;
function batch_(s, ops) {
  if (!Array.isArray(ops) || ops.length > 500) return { ok: false, error: 'invalid', message: 'Send 1–500 operations.' };
  for (let i = 0; i < ops.length; i++) {
    const o = ops[i];
    if (!o || !/^[A-Za-z0-9_\-.~:@+]+(\/[A-Za-z0-9_\-.~:@+]+)+$/.test(o.path || '') || (o.op !== 'set' && o.op !== 'del')) return { ok: false, error: 'invalid', message: 'Bad operation at #' + i };
    if (o.op === 'set' && (!o.data || typeof o.data !== 'object' || Array.isArray(o.data))) return { ok: false, error: 'invalid', message: 'Missing data at #' + i };
    if (!RECORD_PATH_.test(o.path)) return { ok: false, error: 'invalid', message: 'Not a record path at #' + i };
    if (!canWrite_(s, o.op, o.path)) return { ok: false, error: 'forbidden', message: 'No permission to change ' + o.path };
  }
  const lock = LockService.getScriptLock();
  lock.waitLock(20000);
  try {
    const store = load_(); // re-read inside the lock
    const actor = s.email + (s.kind === 'platform' ? ' (Lightech)' : '');
    const merged = ops.map(function (o) {
      if (o.op !== 'set') return o;
      let d = keepSecrets_(store, o.path, o.data);
      const old = data_(store, o.path);
      if (s.kind !== 'platform' && /^ws\/[^/]+$/.test(o.path)) { // login code & status are governed by Lightech only
        d.slug = (old || {}).slug; d.status = (old || {}).status || 'active';
        if (s.role !== 'superadmin') d.accounts = protectAccounts_(old && old.accounts, d.accounts, 'superadmin', s.accountId);
      }
      if (s.kind === 'platform' && o.path === 'platform/main' && s.role !== 'owner' && old) d = selfOnly_(old, d, s.adminId);
      return { op: 'set', path: o.path, data: d };
    });
    const ts = writeDocs_(store, merged, actor);
    auditMany_(ops.map(function (o) { return [new Date(), actor, companyOf_(o.path), o.op === 'del' ? 'delete' : 'save', o.path, summary_(o)]; }));
    return { ok: true, now: ts };
  } finally { lock.releaseLock(); }
}
function changes_(s, since, t0) {
  // Rows that became invisible (deleted or out of scope) are reported as deleted so clients drop them.
  const rows = s.store.rows.filter(function (r) { return r.updatedAt > since && inCompany_(s, r.path); });
  return {
    ok: true, now: t0,
    docs: rows.map(function (r) { return r.deleted || !canRead_(s, r.path) ? { path: r.path, deleted: true } : { path: r.path, data: redact_(s, r.path, JSON.parse(r.json)) }; })
  };
}
function auditList_(s, limit) {
  if (s.kind !== 'platform' && s.role !== 'superadmin' && s.role !== 'admin') return { ok: false, error: 'forbidden', message: 'No access.' };
  return { ok: true, rows: auditRows_(s.kind === 'platform' ? null : s.wsId, Math.min(Number(limit) || 200, 1000)) };
}

// Password hashes never leave the server; incoming records without a hash keep the stored one.
function redact_(s, path, d) {
  if (path === 'platform/main' || /^ws\/[^/]+$/.test(path)) {
    const key = path === 'platform/main' ? 'admins' : 'accounts';
    d = JSON.parse(JSON.stringify(d));
    (d[key] || []).forEach(function (a) { a.defaultPw = isLegacyDemo_(a); delete a.pw; delete a.salt; });
    if (s.role === 'client' && s.kind === 'tenant') d[key] = (d[key] || []).map(function (a) { return a.id === s.accountId ? a : { id: a.id, name: a.name, role: a.role, mentorId: a.mentorId || '', active: a.active }; });
    return d;
  }
  if (visibility_(s, path) === 'numbers') { // leaderboard & funnel only: no names, phones, emails or notes
    return { id: d.id, ownerId: d.ownerId, stageId: d.stageId, value: d.value, source: d.source, programId: d.programId,
      createdAt: d.createdAt, updatedAt: d.updatedAt, wonAt: d.wonAt, lostAt: d.lostAt, lostReason: d.lostReason,
      history: (d.history || []).map(function (h) { return { at: h.at, from: h.from, to: h.to }; }), restricted: true };
  }
  return d;
}
function keepSecrets_(store, path, d) {
  if (!(path === 'platform/main' || /^ws\/[^/]+$/.test(path))) return d;
  const key = path === 'platform/main' ? 'admins' : 'accounts';
  const old = data_(store, path) || {};
  const byId = {};
  (old[key] || []).forEach(function (a) { byId[a.id] = a; });
  d = JSON.parse(JSON.stringify(d));
  const demo = !!(d.config && d.config.demoLogin); // practice workspaces with one-click demo sign-in skip the first-sign-in step
  (d[key] || []).forEach(function (a) {
    delete a.defaultPw;
    // Server-owned flag: a password set by someone else must be changed at next sign-in; otherwise keep what is stored.
    if (a.pw && !demo) a.mustChange = true;
    else { delete a.mustChange; if (byId[a.id] && byId[a.id].mustChange) a.mustChange = true; }
    if (!a.pw && byId[a.id]) { a.pw = byId[a.id].pw; a.salt = byId[a.id].salt; }
  });
  return d;
}

// A company admin cannot touch Owner accounts or create new Owners; only the Owner can.
function protectAccounts_(oldList, newList, protectedRole, selfId) {
  oldList = oldList || []; newList = newList || [];
  const oldById = {};
  oldList.forEach(function (a) { oldById[a.id] = a; });
  const out = [];
  newList.forEach(function (a) {
    const prev = oldById[a.id];
    if (prev && prev.role === protectedRole) { out.push(prev); return; }            // owner records stay exactly as they were
    if (a.role === protectedRole) { if (prev) { a.role = prev.role; } else return; } // no promotion to owner
    out.push(a);
  });
  oldList.forEach(function (a) { if (a.role === protectedRole && !out.some(function (x) { return x.id === a.id; })) out.push(a); }); // owners cannot be removed
  return out;
}
// A Lightech Admin (not Super Admin) may only change their own name, email and password.
function selfOnly_(old, d, selfId) {
  const next = JSON.parse(JSON.stringify(old));
  const mine = (d.admins || []).filter(function (a) { return a.id === selfId; })[0];
  next.admins = (next.admins || []).map(function (a) {
    if (a.id !== selfId || !mine) return a;
    const r = JSON.parse(JSON.stringify(a));
    r.name = mine.name; r.email = mine.email;
    if (mine.pw) { r.pw = mine.pw; r.salt = mine.salt; }
    return r;
  });
  return next;
}

// ───────────────────────────────────────────────────────── storage helpers (in-memory store, persisted by the host)
function data_(store, path) { const r = store.byPath[path]; return r && !r.deleted ? JSON.parse(r.json) : null; }
function metas_(store) { return store.rows.filter(function (r) { return r.parent === 'ws' && !r.deleted; }).map(function (r) { return { id: r.path.split('/')[1], data: JSON.parse(r.json) }; }); }
function slugOf_(w) { return String(w.data.slug || w.data.preset || w.data.name || '').toLowerCase(); }
function companyOf_(path) { const p = path.split('/'); return p[0] === 'ws' ? p[1] : 'lightech'; }
function summary_(o) { if (o.op === 'del') return ''; const d = o.data || {}; return String(d.name || d.leadId || '').slice(0, 80); }
function writeDocs_(store, ops, actor) {
  let ts = Math.max(Date.now(), store.maxTs || 0);
  ops.forEach(function (o) {
    ts += 1; // strictly increasing so polling never misses a write in the same millisecond
    const parent = o.path.split('/').slice(0, -1).join('/');
    const json = o.op === 'set' ? JSON.stringify(o.data) : '';
    const ex = store.byPath[o.path];
    if (!ex && !json) return;
    const r = ex || { path: o.path, parent: parent };
    r.json = json; r.deleted = !json; r.updatedAt = ts; r.updatedBy = actor;
    if (!ex) { store.rows.push(r); store.byPath[o.path] = r; }
    store.pending[o.path] = r;
  });
  store.maxTs = ts;
  return ts;
}

// ───────────────────────────────────────────────────────── crypto & misc
// New passwords: PBKDF2-SHA256 ("pbkdf2$<iterations>$<hex>"). Older SHA-256 hashes (set by an admin in the
// browser) still verify, and are upgraded when the person chooses their own password at first sign-in.
const PBKDF2_ITER = 120000;
function sha256Hex_(s) { return createHash('sha256').update(String(s), 'utf8').digest('hex'); }
function sameHex_(a, b) { a = Buffer.from(String(a)); b = Buffer.from(String(b)); return a.length === b.length && timingSafeEqual(a, b); }
function checkPassword_(acc, pw) {
  if (!acc || !acc.pw) return false;
  const m = /^pbkdf2\$(\d+)\$([0-9a-f]+)$/.exec(acc.pw);
  if (m) return sameHex_(m[2], pbkdf2Sync(String(pw), String(acc.salt || ''), Number(m[1]), 32, 'sha256').toString('hex'));
  return sameHex_(acc.pw, sha256Hex_((acc.salt || '') + ':' + pw));
}
const isLegacyDemo_ = function (a) { return !!a.pw && a.pw.indexOf('pbkdf2$') !== 0 && checkPassword_(a, 'demo'); };
function setPassword_(acc, pw) {
  acc.salt = randomBytes(16).toString('hex');
  acc.pw = 'pbkdf2$' + PBKDF2_ITER + '$' + pbkdf2Sync(String(pw), acc.salt, PBKDF2_ITER, 32, 'sha256').toString('hex');
}
function randomPassword_() { // 12 characters, no look-alikes (0/O, 1/l/I)
  const abc = 'abcdefghijkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  const b = randomBytes(12);
  let s = '';
  for (let i = 0; i < 12; i++) s += abc[b[i] % abc.length];
  return s;
}
// Any signed-in person changes their own password (old one required); clears the first-sign-in flag.
function changePassword_(s, req) {
  const next = String(req.newPassword || '');
  if (next.length < 8) return { ok: false, error: 'invalid', message: 'Use at least 8 characters.' };
  const store = load_();
  const path = s.kind === 'platform' ? 'platform/main' : 'ws/' + s.wsId;
  const doc = data_(store, path);
  const key = s.kind === 'platform' ? 'admins' : 'accounts';
  const id = s.kind === 'platform' ? s.adminId : s.accountId;
  const acc = ((doc || {})[key] || []).filter(function (a) { return a.id === id; })[0];
  if (!acc || !checkPassword_(acc, String(req.oldPassword || ''))) return { ok: false, error: 'invalid', message: 'Current password is wrong.' };
  if (checkPassword_(acc, next)) return { ok: false, error: 'invalid', message: 'Choose a different password.' };
  setPassword_(acc, next); delete acc.mustChange;
  writeDocs_(store, [{ op: 'set', path: path, data: doc }], s.email);
  audit_(s.email, s.wsId || 'lightech', 'password', path, 'changed own password');
  return { ok: true };
}

return { handle_: handle_, VERSION: VERSION, _test: { checkPassword_: checkPassword_, setPassword_: setPassword_, randomPassword_: randomPassword_, sha256Hex_: sha256Hex_ } };
}


// ─────────────────────────────────────────────────────────────── server/pg.js
/**
 * PostgreSQL host for server/core.js (Supabase or any Postgres 14+).
 *
 * One request = one database transaction:
 *   1. writers take a global advisory lock (sign-ins, saves and form submissions are serialized; readers never wait)
 *   2. the records this request may touch are loaded: the platform row, every company row, and the leads /
 *      sessions / clients of the signed-in person's company only (all companies for a Lightech console session)
 *   3. core.handle_() runs on that snapshot
 *   4. pending record writes, audit rows and session / rate-limit keys are saved before COMMIT
 *
 * `sql` is a postgres.js client (npm "postgres"); it is passed in so the same file runs in Deno (Edge Function)
 * and Node (tests).
 */

const LOCK_KEY = 7731001;
const KINDS = ['leads', 'sessions', 'clients'];
const WRITERS = new Set(['setup', 'login', 'capture', 'password', 'logout', 'batch']);


function createApi(sql, opts) {
  opts = opts || {};
  const log = opts.log || function () {};

  return async function api(req) {
    if (!req || typeof req !== 'object' || Array.isArray(req)) return { ok: false, error: 'invalid', message: 'Bad request.' };
    const action = String(req.action || '');
    if (action === 'ping' && opts.fastPing) return { ok: true, version: VERSION };
    const writer = WRITERS.has(action);
    try {
      return await sql.begin(writer ? 'isolation level read committed' : 'isolation level repeatable read read only', async function (tx) {
        if (writer) await tx`select pg_advisory_xact_lock(${LOCK_KEY})`;
        const now = Date.now();
        const host = await loadHost(tx, req, action, now, writer);
        const core = createCore(host);
        const res = core.handle_(req);
        if (writer) await flush(tx, host, now);
        else if (Object.keys(host.store.pending).length || host.auditQueue.length || host.cache.dirty.size) throw new Error('write in a read-only request: ' + action);
        return res;
      });
    } catch (err) {
      log('api error', action, err && err.stack || err);
      return { ok: false, error: 'server', message: 'Server error. Please try again.' };
    }
  };
}

// ───────────────────────────────────────────────────────── load
async function loadHost(tx, req, action, now, writer) {
  const kvRows = await tx`select key, value, expires_at from kv where expires_at > ${now}`;
  const cache = makeCache(kvRows, now);

  const store = { rows: [], byPath: {}, pending: {}, maxTs: 0 };
  const add = function (path, parent, r) {
    const row = { path: path, parent: parent, json: r.deleted || r.data == null ? '' : JSON.stringify(r.data), updatedAt: Number(r.updated_at), updatedBy: r.updated_by || '', deleted: !!r.deleted || r.data == null };
    store.rows.push(row); store.byPath[path] = row;
  };
  const plat = await tx`select id, data, updated_at, updated_by, deleted from platform`;
  plat.forEach(function (r) { add('platform/' + r.id, 'platform', r); });
  const comps = await tx`select id, data, updated_at, updated_by, deleted, slug from companies`;
  comps.forEach(function (r) { add('ws/' + r.id, 'ws', r); });

  // Which companies' records does this request need?
  let wsIds = [];
  if (action === 'capture') {
    const slug = String(req.slug || '').trim().toLowerCase();
    wsIds = comps.filter(function (c) { return !c.deleted && c.slug === slug; }).map(function (c) { return c.id; });
  } else if (req.token) {
    const raw = cache.get('tok:' + String(req.token));
    let s = null;
    try { s = raw ? JSON.parse(raw) : null; } catch (e) { s = null; }
    if (s && s.kind === 'platform') wsIds = comps.map(function (c) { return c.id; });
    else if (s && s.wsId) wsIds = [s.wsId];
  }
  if (wsIds.length) {
    for (const k of KINDS) {
      const rows = await tx`select company_id, id, data, updated_at, updated_by, deleted from ${tx(k)} where company_id in ${tx(wsIds)}`;
      rows.forEach(function (r) { add('ws/' + r.company_id + '/' + k + '/' + r.id, 'ws/' + r.company_id + '/' + k, r); });
    }
  }
  if (writer) {
    const m = await tx`select greatest(
      (select max(updated_at) from platform), (select max(updated_at) from companies), (select max(updated_at) from leads),
      (select max(updated_at) from sessions), (select max(updated_at) from clients)) as m`;
    store.maxTs = Number(m[0].m) || 0;
  }

  let auditRows = [];
  if (action === 'audit') {
    const s = req.token ? cache.get('tok:' + String(req.token)) : null;
    const sess = s ? JSON.parse(s) : null;
    if (sess) {
      auditRows = sess.kind === 'platform'
        ? await tx`select at, actor, company, action, path, detail from audit_log order by id desc limit 1000`
        : await tx`select at, actor, company, action, path, detail from audit_log where company = ${String(sess.wsId || '')} order by id desc limit 1000`;
    }
  }
  let setupCode = '';
  if (action === 'setup') {
    const r = await tx`select code from app_setup where id = 1`;
    setupCode = r.length ? r[0].code : '';
  }

  const host = {
    store: store,
    cache: cache,
    auditQueue: [],
    setupConsumed: false,
    audit: function (row) { host.auditQueue.push(row); },
    auditRows: function (wsId, limit) {
      return auditRows.filter(function (r) { return wsId == null || r.company === wsId; }).slice(0, limit).map(function (r) {
        return { time: new Date(r.at).toISOString(), actor: r.actor, company: r.company, action: r.action, path: r.path, detail: r.detail };
      });
    },
    setupCode: function () { return setupCode; },
    consumeSetup: function () { host.setupConsumed = true; },
    log: function () {}
  };
  return host;
}

// Session tokens, failed-sign-in counters and rate limits (seconds-based TTL, like a cache).
function makeCache(rows, now) {
  const m = new Map();
  rows.forEach(function (r) { m.set(r.key, { value: r.value, exp: Number(r.expires_at) }); });
  const dirty = new Map(); // key → { value, exp } | null (removed)
  return {
    dirty: dirty,
    get: function (k) { const e = m.get(k); return e && e.exp > now ? e.value : null; },
    put: function (k, v, seconds) { const e = { value: String(v), exp: now + Number(seconds) * 1000 }; m.set(k, e); dirty.set(k, e); },
    remove: function (k) { m.delete(k); dirty.set(k, null); }
  };
}

// ───────────────────────────────────────────────────────── save
async function flush(tx, host, now) {
  const rows = Object.keys(host.store.pending).map(function (p) { return host.store.pending[p]; });
  for (const r of rows) {
    const parts = r.path.split('/');
    const data = r.deleted ? null : r.json;
    if (parts[0] === 'platform' && parts.length === 2) {
      await tx`insert into platform (id, data, updated_at, updated_by, deleted) values (${parts[1]}, ${data}::text::jsonb, ${r.updatedAt}, ${r.updatedBy || ''}, ${r.deleted})
        on conflict (id) do update set data = excluded.data, updated_at = excluded.updated_at, updated_by = excluded.updated_by, deleted = excluded.deleted`;
    } else if (parts[0] === 'ws' && parts.length === 2) {
      await tx`insert into companies (id, data, updated_at, updated_by, deleted) values (${parts[1]}, ${data}::text::jsonb, ${r.updatedAt}, ${r.updatedBy || ''}, ${r.deleted})
        on conflict (id) do update set data = excluded.data, updated_at = excluded.updated_at, updated_by = excluded.updated_by, deleted = excluded.deleted`;
    } else if (parts[0] === 'ws' && parts.length === 4 && KINDS.indexOf(parts[2]) >= 0) {
      await tx`insert into ${tx(parts[2])} (company_id, id, data, updated_at, updated_by, deleted) values (${parts[1]}, ${parts[3]}, ${data}::text::jsonb, ${r.updatedAt}, ${r.updatedBy || ''}, ${r.deleted})
        on conflict (company_id, id) do update set data = excluded.data, updated_at = excluded.updated_at, updated_by = excluded.updated_by, deleted = excluded.deleted`;
    } else {
      throw new Error('unsupported path ' + r.path);
    }
  }
  for (const a of host.auditQueue) {
    await tx`insert into audit_log (at, actor, company, action, path, detail)
      values (${new Date(a[0])}, ${String(a[1] || '')}, ${String(a[2] || '')}, ${String(a[3] || '')}, ${String(a[4] || '')}, ${String(a[5] || '').slice(0, 500)})`;
  }
  for (const [k, e] of host.cache.dirty) {
    if (e) await tx`insert into kv (key, value, expires_at) values (${k}, ${e.value}, ${e.exp}) on conflict (key) do update set value = excluded.value, expires_at = excluded.expires_at`;
    else await tx`delete from kv where key = ${k}`;
  }
  if (host.setupConsumed) await tx`delete from app_setup`;
  if (Math.random() < 0.05) await tx`delete from kv where expires_at < ${now}`; // housekeeping
}


// ─────────────────────────────────────────────────────────────── server/http.js
/**
 * HTTP layer (Web-standard Request → Response), shared by the Supabase Edge Function and the tests.
 *   POST <url>   body: JSON { action, token?, ... }  (sent as text/plain so browsers skip the CORS preflight)
 *   GET  <url>   health check: { ok, service, version }
 * CORS: allowed origins come from ALLOWED_ORIGINS (comma-separated); "*" or empty allows any origin, which is safe
 * here because sign-in uses a bearer token in the body, never cookies.
 */
const MAX_BODY = 2 * 1024 * 1024; // 2 MB: 500 records per batch fits comfortably

function createHandler(api, opts) {
  opts = opts || {};
  const allowed = String(opts.allowedOrigins || '').split(',').map(function (s) { return s.trim().replace(/\/$/, ''); }).filter(Boolean);
  const anyOrigin = !allowed.length || allowed.indexOf('*') >= 0;
  const service = opts.service || 'lightech-mentoring-app';

  function cors(req) {
    const origin = req.headers.get('origin') || '';
    const h = { 'Access-Control-Allow-Methods': 'POST, GET, OPTIONS', 'Access-Control-Allow-Headers': 'content-type, authorization, apikey, x-client-info', 'Access-Control-Max-Age': '86400', Vary: 'Origin' };
    if (anyOrigin) h['Access-Control-Allow-Origin'] = '*';
    else if (allowed.indexOf(origin) >= 0) h['Access-Control-Allow-Origin'] = origin;
    return h;
  }
  function json(req, status, obj) {
    return new Response(JSON.stringify(obj), { status: status, headers: Object.assign({ 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', 'X-Content-Type-Options': 'nosniff' }, cors(req)) });
  }

  return async function handle(req) {
    if (req.method === 'OPTIONS') return new Response(null, { status: 204, headers: cors(req) });
    if (req.method === 'GET') return json(req, 200, { ok: true, service: service, version: opts.version || '' });
    if (req.method !== 'POST') return json(req, 405, { ok: false, error: 'invalid', message: 'Use POST.' });
    const origin = req.headers.get('origin');
    if (origin && !anyOrigin && allowed.indexOf(origin) < 0) return json(req, 403, { ok: false, error: 'forbidden', message: 'Origin not allowed.' });
    let text = '';
    try { text = await req.text(); } catch (e) { return json(req, 400, { ok: false, error: 'invalid', message: 'Bad request.' }); }
    if (text.length > MAX_BODY) return json(req, 413, { ok: false, error: 'invalid', message: 'Request too large.' });
    let body;
    try { body = JSON.parse(text || '{}'); } catch (e) { return json(req, 200, { ok: false, error: 'invalid', message: 'Bad JSON.' }); }
    const res = await api(body);
    return json(req, 200, res);
  };
}


// ─────────────────────────────────────────────────────────────── entry point
const sql = postgres(Deno.env.get('SUPABASE_DB_URL'), { prepare: false, max: 3, idle_timeout: 20, connect_timeout: 10, onnotice: () => {} });
const handler = createHandler(createApi(sql, { log: (...a) => console.error(...a) }), { version: VERSION, allowedOrigins: Deno.env.get('ALLOWED_ORIGINS') || '' });
Deno.serve(handler);
