// Bundles server/core.js + server/pg.js + server/http.js into ONE file: supabase/functions/api/index.ts.
// One file means it can be deployed with the Supabase CLI or pasted into Dashboard → Edge Functions → Editor.
//   node scripts/build-edge.mjs          write the bundle
//   node scripts/build-edge.mjs --check  fail if the committed bundle is out of date (run by npm test)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'supabase', 'functions', 'api', 'index.ts');
const strip = (f) => fs.readFileSync(path.join(root, 'server', f), 'utf8')
  .split('\n')
  .filter((l) => !/^import .* from '\.\/.*';$/.test(l) && !/^export \{ VERSION \};$/.test(l))
  .map((l) => l.replace(/^export (function|const) /, '$1 '))
  .join('\n');

const body = `// @ts-nocheck
// GENERATED by scripts/build-edge.mjs from server/core.js, server/pg.js and server/http.js. Do not edit by hand.
//
// Lightech Mentoring App API — Supabase Edge Function "api".
// Env (set automatically by Supabase): SUPABASE_DB_URL.  Optional: ALLOWED_ORIGINS="https://crm.example.com".
// "Verify JWT" must be OFF for this function: the app signs people in itself (supabase/config.toml does this).
import postgres from 'npm:postgres@3.4.4';

${strip('core.js').replace(/^import \{ createHash[^\n]*\n/m, "import { createHash, pbkdf2Sync, randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';\n")}

// ─────────────────────────────────────────────────────────────── server/pg.js
${strip('pg.js')}

// ─────────────────────────────────────────────────────────────── server/http.js
${strip('http.js')}

// ─────────────────────────────────────────────────────────────── entry point
const sql = postgres(Deno.env.get('SUPABASE_DB_URL'), { prepare: false, max: 3, idle_timeout: 20, connect_timeout: 10, onnotice: () => {} });
const handler = createHandler(createApi(sql, { log: (...a) => console.error(...a) }), { version: VERSION, allowedOrigins: Deno.env.get('ALLOWED_ORIGINS') || '' });
Deno.serve(handler);
`;

if (process.argv.includes('--check')) {
  const cur = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
  if (cur !== body) { console.error('supabase/functions/api/index.ts is out of date: run node scripts/build-edge.mjs'); process.exit(1); }
  console.log('edge bundle up to date');
} else {
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, body);
  console.log('wrote ' + path.relative(root, out) + ' (' + body.length + ' bytes)');
}
