// Writes the app shell into server/Code.gs so the Apps Script web app serves the whole app (no separate hosting).
// The shell loads app.css / presets.js / app.js from jsDelivr, pinned to one commit of this public repo.
//   ASSET_REF=<commit sha> node scripts/build-gas.mjs     (default: the current HEAD)
//   node scripts/build-gas.mjs --check                    (exit 1 if Code.gs is out of date)
import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const codePath = join(root, 'server', 'Code.gs');
const check = process.argv.includes('--check');
const code = readFileSync(codePath, 'utf8');
const START = '// ── app shell (generated by scripts/build-gas.mjs; do not edit by hand) ──';
const END = '// ── end app shell ──';
const currentRef = (code.match(/const ASSET_BASE = 'https:\/\/cdn\.jsdelivr\.net\/gh\/oasys-lightrees\/mentoring_app@([0-9a-f]{7,40})\//) || [])[1];
const ref = process.env.ASSET_REF || (check ? currentRef : execFileSync('git', ['rev-parse', 'HEAD'], { cwd: root }).toString().trim());
const html = readFileSync(join(root, 'index.html'), 'utf8');
const body = html.split(/<body[^>]*>/)[1].split('<script')[0].trim();
const shell = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap">
<link rel="stylesheet" href="__ASSETS__assets/app.css">
</head>
<body>
${body}
<script>window.MCRM_CONFIG = __CONFIG__;</script>
<script src="__ASSETS__assets/presets.js"></script>
<script src="__ASSETS__assets/app.js"></script>
</body>
</html>`;
const block = `${START}
const ASSET_BASE = 'https://cdn.jsdelivr.net/gh/oasys-lightrees/mentoring_app@${ref}/';
const APP_SHELL = ${JSON.stringify(shell)};
${END}`;
const re = new RegExp(START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '[\\s\\S]*?' + END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
const next = re.test(code) ? code.replace(re, block) : code.trimEnd() + '\n\n' + block + '\n';
if (check) { if (next !== code) { console.error('server/Code.gs app shell is out of date: run node scripts/build-gas.mjs'); process.exit(1); } console.log('Code.gs app shell up to date'); process.exit(0); }
writeFileSync(codePath, next);
console.log(`server/Code.gs app shell written (assets @${ref.slice(0, 7)})`);
